#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




//Creates variables to store the red, green, and blue values


void turnRightAndForward()
{
     turnRight(150, degrees, 100);

	 	 forward(5, rotations, 100);
}

void incrementForwardUntilIntersection()
{
	long redValue;
	long greenValue;
	long blueValue;

		while(true) {
			forward(.5, rotations, 100);
			getColorRGB(colorSensor, redValue, greenValue, blueValue);

			writeDebugStreamLine("Colour detected: %d, %d, %d", redValue, greenValue, blueValue);
			sleep(100);
		}
}


task main()
{

	turnRightAndForward();

	//redValue;
	//long greenValue;
	//long blueValue;




		//getUSDistance(sonarSensor);

  //forward(1, rotations, 100);
  //forward(1, rotations, 100);
	//getColorRGB(colorSensor, redValue, greenValue, blueValue);
	//writeDebugStreamLine("Colour detected: %d, %d, %d", redValue, greenValue, blueValue)

}


